api:
  replicaCount: 1
  image:
    repository: "255945442255.dkr.ecr.ap-southeast-1.amazonaws.com/ce10grp2-app/api"
    tag: 9f26e98
  env:
    NODE_ENV: development
    DEBUG: "true"
    REDIS_URL: "redis://redis:6379"
frontend:
  replicaCount: 1
  image:
    repository: "255945442255.dkr.ecr.ap-southeast-1.amazonaws.com/ce10grp2-app/frontend"
    tag: 9f26e98
  env:
    REACT_APP_API_URL: "https://a5f708e5cee604f7c860dc7c5fd7702a-43145271.ap-southeast-1.elb.amazonaws.com/api"
ingress:
  hosts:
    - host: "a5f708e5cee604f7c860dc7c5fd7702a-43145271.ap-southeast-1.elb.amazonaws.com"
      paths:
        - path: /api
          pathType: Prefix
          service: api
        - path: /
          pathType: Prefix
          service: frontend
