# Global configuration
global:
  aws:
    accountId: "255945442255" # <-- VARIABLE
    region: "ap-southeast-1" # <-- VARIABLE

# API Service Configuration
api:
  enabled: true
  replicaCount: 2
  image:
    repository: "ce10grp2-app/api"
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
    name: "api-service"

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  env:
    NODE_ENV: production
    REDIS_URL: "redis://redis:6379"
    PORT: "3000"

# Frontend Service Configuration
frontend:
  enabled: true
  replicaCount: 2
  image:
    repository: "ce10grp2-app/frontend"
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80
    targetPort: 80
    name: "frontend-service"

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# redis
redis:
  enabled: true
  replicaCount: 1

  image:
    repository: "redis"
    tag: "7-alpine"
    pullPolicy: IfNotPresent

  service:
    port: 6379

  persistence:
    enabled: true
    size: "1Gi"
    storageClassName: "gp2" # Or your preferred storage class

  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Ingress Configuration
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /api
          pathType: Prefix
          service: api
        - path: /
          pathType: Prefix
          service: frontend
