api:
  replicaCount: 2
  image:
    tag: uat
  env:
    NODE_ENV: staging

frontend:
  replicaCount: 2
  image:
    tag: uat
  env:
    REACT_APP_API_URL: ""

ingress:
  hosts:
    - host: ""
      paths:
        - path: /api
          pathType: Prefix
          service: api
        - path: /
          pathType: Prefix
          service: frontend
