api:
  replicaCount: 3
  image:
    tag: prod
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  env:
    NODE_ENV: production

frontend:
  replicaCount: 3
  image:
    tag: prod
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  env:
    REACT_APP_API_URL: ""

ingress:
  hosts:
    - host: ""
      paths:
        - path: /api
          pathType: Prefix
          service: api
        - path: /
          pathType: Prefix
          service: frontend
