# k8s/database/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: lingo-game
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  type: ClusterIP
