# k8s/api/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: lingo-game
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
