apiVersion: v1
kind: Service
metadata:
  name: ce10grp2-api-service
  namespace: {{ .Release.Namespace }}   # e.g., ce10grp2-dev or ce10grp2-uat
  labels:
    app.kubernetes.io/name: ce10grp2-app
    app.kubernetes.io/instance: {{ .Release.Namespace }} 
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: ce10grp2-app
    app.kubernetes.io/instance: {{ .Release.Namespace }} 
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 3000
      targetPort: 3000