apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ce10grp2-uat
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tor-wei/ce10grp2-app
    path: helm/ce10grp2-app
    targetRevision: uat
    helm:
      valueFiles:
        - values.yaml
        - values-uat.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ce10grp2-uat
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
