# .github/workflows/cd-backend.yml
name: CD - Backend (API)

on:
  push:
    branches:
      - dev
    paths:
      - "api/**"
      - ".github/workflows/cd-backend.yml"

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ce10grp2-app/api

jobs:
  build-backend:
    name: Build and Push API Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    outputs:
      image_tag: ${{ steps.vars.outputs.sha }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Image Tag variable
        id: vars
        run: echo "sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: ${{ github.run_id }}-build-backend
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push API Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.vars.outputs.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./api
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:dev
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:dev

      - name: Update Helm Chart for Dev
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
          yq -i '.api.image.tag = "${{ steps.vars.outputs.sha }}"' helm/ce10grp2-app/values-dev.yaml

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add helm/ce10grp2-app/values-dev.yaml
          git commit -m "Update dev api image tag to ${{ steps.vars.outputs.sha }}"

      - name: Create Pull Request to Dev
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update dev api image tag to ${{ steps.vars.outputs.sha }}"
          title: "CI: Update dev api image tag to ${{ steps.vars.outputs.sha }}"
          body: "Automated PR to deploy API version `${{ steps.vars.outputs.sha }}` to the DEV environment."
          branch: "promote-dev-api-${{ steps.vars.outputs.sha }}"
          base: "dev"

  scan-backend:
    name: Security Scan API Image
    runs-on: ubuntu-latest
    needs: build-backend
    permissions:
      id-token: write
      contents: read
      security-events: write

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: ${{ github.run_id }}-scan-backend
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Run Trivy scan on API image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ needs.build-backend.outputs.image_tag }}"
          format: "sarif"
          output: "trivy-api-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-api-results.sarif"
          category: backend
