name: Deploy to Kubernetes

on:
  push:
    branches:
      - main # Deploys to 'prod'
      - uat # Deploys to 'uat'
      - dev # Deploys to 'dev'

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options: [dev, uat, prod]
        default: "dev"

jobs:
  deploy:
    name: Deploy to K8s Namespace
    runs-on: ubuntu-latest

    environment:
      # Set environment based on branch or manual input
      name: ${{ (github.ref == 'refs/heads/main' && 'prod') || (github.ref == 'refs/heads/uat' && 'uat') || (github.ref == 'refs/heads/dev' && 'dev') || github.event.inputs.environment }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Environment Specifics
        id: set_env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.event.inputs.environment }}" == "prod" ]]; then
            echo "K8S_OVERLAY_PATH=k8s/overlays/prod" >> $GITHUB_ENV
            echo "CLUSTER_NAME=${{ secrets.PROD_CLUSTER_NAME }}" >> $GITHUB_ENV
          # CORRECTED: Changed 'staging' to 'uat' to match the branch name
          elif [[ "${{ github.ref }}" == "refs/heads/uat" || "${{ github.event.inputs.environment }}" == "uat" ]]; then
            echo "K8S_OVERLAY_PATH=k8s/overlays/uat" >> $GITHUB_ENV
            echo "CLUSTER_NAME=${{ secrets.NON_PROD_CLUSTER_NAME }}" >> $GITHUB_ENV
          # CORRECTED: Changed 'develop' to 'dev' to match the branch name
          elif [[ "${{ github.ref }}" == "refs/heads/dev" || "${{ github.event.inputs.environment }}" == "dev" ]]; then
            echo "K8S_OVERLAY_PATH=k8s/overlays/dev" >> $GITHUB_ENV
            echo "CLUSTER_NAME=${{ secrets.NON_PROD_CLUSTER_NAME }}" >> $GITHUB_ENV
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Kubeconfig
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}

      - name: Deploy to K8s Cluster with Kustomize
        run: kubectl apply -k ${{ env.K8S_OVERLAY_PATH }}
